server:
  servlet:
    context-path: /clinica-medica/api

spring:    
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/clinicaMedicaDB}
      auto-index-creation: true
