server:
  servlet:
    context-path: /clinica-medica/api

spring:    
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://clinicaMedicaDB:eP9McRwk4KNGQP0o@wakandadev.cjsar7m.mongodb.net/?retryWrites=true&w=majority}
      auto-index-creation: true
     